### ISSUE TITLE
Bouldin Creek Cafe Style Tile Feedback

### ISSUE THREAD

**Issue by dawndelatte** [crowjm/tiy_assignments#5]
v1 - The colors and fonts are definitely representative of your inspiration and adjectives. Because there is not a lot of contrast between the two blues and the two oranges/yellow, I would suggest using them to compliment and keep separate or you may loose hierarchy between them. 

v2 - The paragraph text needs to be larger, especially if it's sitting on the dark blue background. I think the header text is great, very "bouldin" and retro, but I would suggest keeping to h1 - h2 because it looses readability the smaller it gets.

v3 - This font is very readable, and has a retro vibe. I would suggest using something with a more rounded terminal for the h1, as it would be indicative of a neon sign and it would create a little more contrast between the header and sub-header/paragraph texts.

**Comment by jesse-stew** [comment]
Thank you! I really appreciate how specific your feedback is!

v1- I played with some different color choices, and settled on 2 blues and 2 yellows, with darker and lighter shades of each (lighter used in headlines/bigger elements and the darker used in p elements) so that there is some consistency. I also introduced a grey for menu section descriptions.

v2- I added a screenshot of the p text how it is in the Typecast, not just changing the typeface in the file--good catch! I also changed the menu item names to a bold version of Adelle. I agree about the readability issue with Orgovan.

v3- I changed the font to Rooney Sans in different weights for the h1 & h2 elements. The new contrast is great.
