### ISSUE TITLE
style tile

### ISSUE THREAD

**Issue by xinyu0** [crowjm/tiy_assignments#6]
V1 
This one is my favorite. The colors and the typefaces give a friendly vibe. It makes me feel hungry. I don't think the visual hierarchy is as strong as it could be, and the headline may be better if not italic (so it looks a bit different from the subhead)

V2
The fonts on the headline and subhead make me think of retro comic books. It kind of works with the logo. 

V3
The neon sign idea is really cool. But the first 2 snapshots under textures are a little confusing. The first one looks really classy and the 2nd one looks weird.

**Comment by jesse-stew** [comment]
Thanks for the feedback!

v1- I changed the color scheme slightly to create more hierarchy (that was feedback I've gotten across the board so far). The typeface for the h elements is currently in it's regular state, it just has a slight tilt built in to it.

v2- Thank you! It also reminded me of the old auto shop lettering they have in their windows.

v3- I agree, the first texture shot is a little fancy. I pulled it in not so much for the fancy vibe, but because I really liked the way they used bright colors to establish some hierarchy; it's an idea I want to try. The second texture is part of the Welcome To Austin mural that's a couple of blocks from Bouldin. I wanted to pull in bright colors and the vibrant/funky personality of South Austin.
